import { EventCardName } from "@eots/game";
import { IconType } from "react-icons";
import {
  GiFireDash,
  GiElfHelmet,
  GiCoffin,
  GiWheat,
  GiChurch,
  GiCrossedSwords,
  GiMoneyStack,
  GiDeadWood,
  GiScrollQuill,
  GiLovers,
  GiFairyWand,
  GiHoodedFigure,
  GiDesertSkull,
  GiAnvil,
  GiCavalry,
  GiBurningBook,
  GiPirateSkull,
  GiSiegeRam,
  GiBrokenShield,
  GiDragonHead,
  GiGhost,
  GiTemplarShield,
  GiPaintBrush,
  GiDove,
  GiPitchfork,
  GiScrollUnfurled,
  GiCrownedSkull,
  GiCompass,
  GiPrayer,
  GiGoldBar,
  GiCrown,
  GiBrokenHeart,
  GiPoisonBottle,
  GiFire,
  GiSeaSerpent,
  GiSailboat,
  GiWindmill,
} from "react-icons/gi";

export const EVENT_ICONS: Partial<Record<EventCardName, IconType>> = {
  a_kingdom_turns_heretic: GiFireDash,
  allies_in_faerie: GiElfHelmet,
  archprelate_dies: GiCoffin,
  bumper_crops: GiWheat,
  colonial_prelates: GiChurch,
  colonial_rebellion: GiCrossedSwords,
  corruption_scandal: GiMoneyStack,
  crops_fail: GiDeadWood,
  defence_of_the_faith: GiScrollQuill,
  dynastic_marriage: GiLovers,
  faerie_uprising: GiFairyWand,
  foreign_agitators: GiHoodedFigure,
  grand_infidel_dies: GiDesertSkull,
  guild_revolt: GiAnvil,
  headstrong_commander: GiCavalry,
  heretic_rebellion: GiBurningBook,
  infidel_corsairs_raid: GiPirateSkull,
  infidels_invade_faerie: GiSiegeRam,
  lenders_refuse_credit: GiBrokenShield,
  monsters_awake: GiDragonHead,
  mysterious_disappearances: GiGhost,
  orthodox_rebellion: GiTemplarShield,
  patrons_of_the_arts: GiPaintBrush,
  peace_accord_reached: GiDove,
  peasant_rebellion: GiPitchfork,
  prelacy_condemned: GiScrollUnfurled,
  pretender_rebellion: GiCrownedSkull,
  race_to_discovery: GiCompass,
  return_to_orthodoxy: GiPrayer,
  royal_patronage: GiGoldBar,
  royal_succession: GiCrown,
  schism: GiBrokenHeart,
  the_faerie_plague: GiPoisonBottle,
  the_great_fire: GiFire,
  treacherous_creatures: GiSeaSerpent,
  venoa_turns_heretic: GiSailboat,
  zeeland_turns_heretic: GiWindmill,
};
